const data = [
	{
		id: 'panel',
		name: 'Panel',
		code: '#panel{background-image: url(%link%);}',
		url: 'https://classic.margonem.pl/img/panel.png',
		type: 'input',
	},
	{
		id: 'chat',
		name: 'Chat',
		code: '#chat, #chattabs, #chattabs s{background-image: url(%link%);}',
		url: 'https://classic.margonem.pl/img/chat.png',
		type: 'input',
	},
	{
		id: 'chat-left',
		name: 'Lewy chat',
		code: '#chat.left, #chattabs.left, #chat.left #chattabs s{background-image: url(%link%);}',
		url: 'https://classic.margonem.pl/img/chat-left.png',
		type: 'input',
	},
	{
		id: 'alert',
		name: 'Alert',
		code: '#alert .a1, #alert .a3, #alert button, #dlgwin .w1, #staminashop .a1, #staminashop .a3, BUTTON.bal_ok, BUTTON.bal_cancel, BUTTON.bal_yes, BUTTON.bal_no, BUTTON.bal_pay, BUTTON.bal_pay_increase, BUTTON.bal_pay_decrease {background-image: url(%link%) !important;}',
		url: 'https://classic.margonem.pl/img/alert.png',
		type: 'input',
	},
	{
		id: 'alert-inner',
		name: 'Środek alertu',
		code: '#alert, #dlgwin, #staminashop, #upgradeclandepoalert, .MM-alert {background-image: url(%link%) !important;}',
		url: 'https://classic.margonem.pl/img/alert-middle.png',
		type: 'input',
	},
	{
		id: 'closebut',
		name: 'Przycisk X',
		code: '.closebut, .close-but, #pre-premium-panel .close-pre-premium, #recipes .close-but, #chests-window .close-chests-window, #loot-preview .close-but, #quest-log-window .quest-log-close-but{background-image: url(%link%);}',
		url: 'https://classic.margonem.pl/img/b_close.png',
		type: 'input',
	},
	{
		id: 'quests',
		name: 'Questy',
		code: '#quest-log-window{background-image: url(%link%);}',
		url: 'https://classic.margonem.pl/img/window_quest.png',
		type: 'input',
	},
	{
		id: 'clanmenu',
		name: 'Klany',
		code: '#clanmenu{background-image: url(%link%);}',
		url: 'https://classic.margonem.pl/img/clanmenu.png',
		type: 'input',
	},
	{
		id: 'recipes',
		name: 'Rzemiosło',
		code: '#recipes {background-image: url(%link%);}',
		url: 'https://classic.margonem.pl/img/recipes-tab-bg.png',
		type: 'input',
	},
	{
		id: 'conf-title',
		name: 'Tytuł konfiguracji',
		code: '.conf-title{background-image: url(%link%) !important;}',
		url: 'https://classic.margonem.pl/img/conf-title.png',
		type: 'input',
	},
	{
		id: 'config',
		name: 'Konfiguracja',
		code: '#config{background-image: url(%link%) !important;}',
		url: 'https://classic.margonem.pl/img/conf-back.png',
		type: 'input',
	},
	{
		id: 'config-save',
		name: "Przycisk 'Zapisz'",
		code: '#config .save{background-image: url(%link%);}',
		url: 'https://classic.margonem.pl/img/bw_save.png',
		type: 'input',
	},
	{
		id: 'config-cancel',
		name: "Przycisk 'Anuluj'",
		code: '#config .cancel{background-image: url(%link%);}',
		url: 'https://classic.margonem.pl/img/bw_cancel.png',
		type: 'input',
	},
	{
		id: 'change-client',
		name: 'Przycisk zmiany interfejsu',
		code: '.changeClient{background-image: url(%link%);}',
		url: 'https://classic.margonem.pl/img/new_client_button.png',
		type: 'input',
	},
	{
		id: 'checkbox',
		name: 'Checkbox',
		code: '#cfg_options DIV::before, .my-checkbox, .my-checkbox.active{background-image: url(%link%);}',
		url: 'https://classic.margonem.pl/img/checkbox.png',
		type: 'input',
	},
	{
		id: 'mappanel',
		name: 'Panel minimapy',
		code: '#mappanel{background-image: url(%link%);}',
		url: 'https://classic.margonem.pl/img/worldmap.jpg',
		type: 'input',
	},
	{
		id: 'skills',
		name: 'Umiejętności',
		code: '#skills, #skills_title{background-image: url(%link%);}',
		url: 'https://classic.margonem.pl/img/skillsAndBar.png',
		type: 'input',
	},
	{
		id: 'skills-tab-header',
		name: 'Belka umiejętności',
		code: '.skills_tab_header{background-image: url(%link%);}',
		url: 'https://classic.margonem.pl/img/belka_notxt.png',
		type: 'input',
	},
	{
		id: 'friends',
		name: 'Panel przyjaciół',
		code: '#friends{background-image: url(%link%);}',
		url: 'https://classic.margonem.pl/img/fr-window.jpg',
		type: 'input',
	},
	{
		id: 'friends-buttons',
		name: 'Przyciski przyjaciół',
		code: 'DIV.frparty, .chatfr, .delfr, #enadd, #fradd, #frsort, .delen, .frup, .frdn{background-image: url(%link%);}',
		url: 'https://classic.margonem.pl/img/fr-buttons.png',
		type: 'input',
	},
	{
		id: 'window-si',
		name: 'Okno SI',
		code: '.MM-dialog{border-image: url(%link%) 51 64 24 57 fill repeat;}',
		url: 'https://classic.margonem.pl/img/window_si.png',
		type: 'input',
	},
	{
		id: 'audio-buttons',
		name: 'Przyciski audio',
		code: '#startbutton, #shufflebutton, #hdbutton, #volumeSlider .marker{background-image: url(%link);}',
		url: 'https://classic.margonem.pl/img/music_interface.png',
		type: 'input',
	},
	{
		id: 'news-panel',
		name: 'Okno aktualności',
		code: '.news-panel{background-image: url(%link%);}',
		url: 'https://classic.margonem.pl/img/news.png',
		type: 'input',
	},
	{
		id: 'stats',
		name: 'Statystyki',
		code: '#stats{background-image: url(%link%);}',
		url: 'https://classic.margonem.pl/img/stats.png',
		type: 'input',
	},
	{
		id: 'addons',
		name: 'Panel dodatków',
		code: '#addonspanel{background-image: url(%link%);}',
		url: 'https://classic.margonem.pl/img/addons.jpg',
		type: 'input',
	},
	{
		id: 'bg',
		name: 'Tło klanów, dodatków, itp.',
		code: '#clanbox, #inmap, #inmap2wrapper, #addons, #auctions{background-image: url(%link%);}',
		url: 'https://classic.margonem.pl/img/paper512.jpg',
		type: 'input',
	},
	{
		id: 'buttons',
		name: 'Przyciski interfejsu',
		code: '#buttons, #b_recipes, #b_quests, #b_matchmaking, #b_help, #b_clans, #b_pvp, #b_config, #b_map, #b_skills, #b_friends, #b_addons, #b_news, #helpbut, #logoutbut, #bchat{background-image: url(%link%) !important;}',
		url: 'https://classic.margonem.pl/img/if-buttons.png',
		type: 'input',
	},
	{
		id: 'premiumbut',
		name: 'Przycisk Premium',
		code: '#premiumbut{background-image: url(%link%);}',
		url: 'https://classic.margonem.pl/img/B-premium.png',
		type: 'input',
	},
	{
		id: 'premiumshop',
		name: 'Sklep Premium',
		code: '#premiumshop .buymore_ps, #premiumshop .closebutton_ps, #premiumshop, #premiumshop .premiumItem, #premiumshop .item_bg, #premiumshop .promocode_button{background-image: url(%link%);}',
		url: 'https://classic.margonem.pl/img/panel-sl-pl.png',
		type: 'input',
	},
	{
		id: 'calendar',
		name: 'Przycisk kalendarza',
		code: '#new_event_calendar{background-image: url(%link%);}',
		url: 'https://classic.margonem.pl/img/calendar_widget.gif',
		type: 'input',
	},
	{
		id: 'lagmeter',
		name: 'Lagmeter',
		code: '#lagmeter{background-image: url(%link%);}',
		url: 'https://classic.margonem.pl/img/lagometer.png',
		type: 'input',
	},
	{
		id: 'pvpmode',
		name: 'Kulka PvP',
		code: '#pvpmode{background-image: url(%link%);}',
		url: 'https://classic.margonem.pl/img/pvpmode.png',
		type: 'input',
	},
	{
		id: 'shop',
		name: 'Panel sklepu',
		code: '#shop{background-image: url(%link%);}',
		url: 'https://classic.margonem.pl/img/shop.png',
		type: 'input',
	},
	{
		id: 'shop-buttons',
		name: 'Przyciski sklepu',
		code: '#shop_close, #shop_accept, #match-details-wnd .close-match-details-wrapper .close-match-details{background-image: url(%link%);}#shop_recover_items{background: url(%link%) -182px 0}',
		url: 'https://classic.margonem.pl/img/shop-buttons.png',
		type: 'input',
	},
	{
		id: 'sl-buttons',
		name: "Przyciski 'Brakuje SŁ?', itp.",
		code: '#sl_shop_banner{background-image: url(%link%);}#hieronim_button{background: url(%link%) 0px -94px;}#gold_shop_banner{background: url(%link%) 0px -54px;}#lehim_button{background: url(%link%) 0px -127px;}',
		url: 'https://classic.margonem.pl/img/banery_shop.png',
		type: 'input',
	},
	{
		id: 'outfit-shop',
		name: 'Panel sklepu z outfitami',
		code: '#shop.outfit{background-image: url(%link%);}',
		url: 'https://classic.margonem.pl/img/shop-outfit.png',
		type: 'input',
	},
	{
		id: 'auctions',
		name: 'Aukcje',
		code: '#auctions button, #ahtitle, #ahselect, #ah_mylist H5, #ahselect B#b_myah, #auctions .itemcont, #auctions #ah_filter BUTTON{background-image: url(%link%) !important;}',
		url: 'https://classic.margonem.pl/img/auctions.png',
		type: 'input',
	},
	{
		id: 'console',
		name: 'Konsola/dialogi',
		code: '#console, #dialog{background-image: url(%link%);}',
		url: 'https://classic.margonem.pl/img/console-back.jpg',
		type: 'input',
	},
	{
		id: 'battle',
		name: 'Panel walki',
		code: '#battlepanelback, #battlehelp, #battleclose, #battle .border-b{background-image: url(%link%) !important;}',
		url: 'https://classic.margonem.pl/img/battle2.png',
		type: 'input',
	},
	{
		id: 'loots',
		name: 'Okno łupów',
		code: '#loots_l, #loots_r, #loots .loot, #loots B.yes, #loots B.no, #loots_counter, #loots_button, #loots B.need{background-image: url(%link%)}',
		url: 'https://classic.margonem.pl/img/loots.png',
		type: 'input',
	},
	{
		id: 'loots2',
		name: 'Tło okna łupów',
		code: '#loots{border-image-source: url(%link%);}',
		url: 'https://classic.margonem.pl/img/loots2.png',
		type: 'input',
	},
	{
		id: 'battle-switch',
		name: 'Set ekwipunku',
		code: '.MM-battleset-switch-button{background-image: url(%link%);}',
		url: 'https://classic.margonem.pl/img/battle_switch.png',
		type: 'input',
	},
	{
		id: 'skill-switch',
		name: 'Set umiejętności',
		code: '#skillSwitch{background-image: url(%link%) !important;}',
		url: 'https://classic.margonem.pl/img/um_set.gif',
		type: 'input',
	},
	{
		id: 'bottombar',
		name: 'Dolna belka',
		code: '#bottombar{background-image: url(%link%);}',
		url: 'https://classic.margonem.pl/img/bottom-bar.png',
		type: 'input',
	},
	{
		id: 'mm-buttons',
		name: 'Otchłań/różne przyciski',
		code: '.SI-button .left{background:url(%link%);background-position: -443px -229px;}.SI-button .label{background:url(%link%);background-position: -463px -229px;}.SI-button .right{background:url(%link%);background-position: -622px -229px;}#for-you-plug{background:url(%link%) -0px -942px;}.MM-dialog-header-txt, .MM-big-button-header, .MM-big-button.MM-stat-button, .MM-dialog-space .warning-points, .MM-button .content, .MM-button .left, .MM-button .right, .MM-big-button.MM-fight-button, .MM-big-button.MM-rank-button, .MM-queue-button, .MM-big-button MM-eq-button, .MM-eq-button, .MM-eq-button.selected, .season-wnd .reward-wrapper .rage-wrapper, #pre-premium-panel, #chests-window, #matchmaking-summary{background-image: url(%link%);}',
		url: 'https://classic.margonem.pl/img/mm-buttons.png',
		type: 'input',
	},
	{
		id: 'window-bar',
		name: 'Belka okna',
		code: '.MM-dialog-header{background-image: url(%link%);}',
		url: 'https://classic.margonem.pl/img/window_belka.png',
		type: 'input',
	},
	{
		id: 'border-u',
		name: 'Górna ramka',
		code: '#corners img{box-sizing: border-box;display: block;}#corners .border-u{background: url(%link%) no-repeat;height: 7px;padding-left: 799px;width: 799px;}',
		url: 'https://classic.margonem.pl/img/border-u.png',
		type: 'input',
	},
	{
		id: 'border-r',
		name: 'Prawa ramka',
		code: '#corners .border-r{background: url(%link%) no-repeat;height: 537px;padding-left: 6px;width: 6px;}',
		url: 'https://classic.margonem.pl/img/border-r.png',
		type: 'input',
	},
	{
		id: 'border-d',
		name: 'Dolna ramka',
		code: '#corners .border-d{background: url(%link%) no-repeat;height: 7px;padding-left: 799px;width: 799px;}',
		url: 'https://classic.margonem.pl/img/border-d.png',
		type: 'input',
	},
	{
		id: 'border-l',
		name: 'Lewa ramka',
		code: '#corners .border-l{background: url(%link%) no-repeat;height: 537px;padding-left: 6px;width: 6px;}',
		url: 'https://classic.margonem.pl/img/border-l.png',
		type: 'input',
	},
	{
		id: 'trade',
		name: 'Panel handlu',
		code: '#tradebg, #trade BUTTON{background-image: url(%link%);}',
		url: 'https://classic.margonem.pl/img/trade.png',
		type: 'input',
	},
	{
		id: 'alert-input',
		name: 'Input alertu',
		code: '#alert div.mAlertInputContainer input[name="mAlertInput"], #alert div.mAlertInputContainer .bRight, #alert div.mAlertInputContainer .bLeft{background-image: url(%link%);}',
		url: 'https://classic.margonem.pl/img/alert-input.png',
		type: 'input',
	},
	{
		id: 'party',
		name: 'Panel grupy',
		code: '#party{background-image: url(%link%) !important;}',
		url: 'https://i.imgur.com/cVXt9ju.png',
		type: 'input',
	},
	{
		id: 'party-border',
		name: 'Ramka grupy',
		code: '#party img{box-sizing: border-box;display: block;background: url(%link%) no-repeat;height: 7px;padding-left: 150px;width: 150px;}',
		url: 'https://i.imgur.com/uey7NAw.png',
		type: 'input',
	},
	{
		id: 'help-title',
		name: 'Tytuł pomocy',
		code: '#dlgwin .w2{background-image: url(%link%) !important;}',
		url: 'https://classic.margonem.pl/img/help-title.png',
		type: 'input',
	},
	{
		id: 'depo',
		name: 'Depozyt',
		code: '#depo, #depo-title{background-image: url(%link%);}',
		url: 'https://classic.margonem.pl/img/depo.png',
		type: 'input',
	},
	{
		id: 'depo-buttons',
		name: 'Przyciski depozytu',
		code: '#depo BUTTON{background-image: url(%link%);}#depo-gold INPUT {background: url(%link%) no-repeat 0 -228px;}',
		url: 'https://classic.margonem.pl/img/depo-buttons.png',
		type: 'input',
	},
	{
		id: 'loading',
		name: 'Ładowanie gry',
		code: '#loading{background-image: url(%link%);}',
		url: 'https://classic.margonem.pl/img/loading.jpg',
		type: 'input',
	},
	{
		id: 'bm_edit',
		name: 'Panel mistrzostwa walk',
		code: '#bm_edit_panel{background-image: url(%link%);}',
		url: 'https://classic.margonem.pl/img/bmmenu.png',
		type: 'input',
	},
	{
		id: 'crafting-window',
		name: 'Tło rzemiosła',
		code: '#crafting{background-image: url(%link%);}',
		url: 'https://classic.margonem.pl/img/crafting-window.png',
		type: 'input',
	},
	{
		id: 'barter',
		name: 'Barter',
		code: '#barter-window{background-image: url(%link%);}',
		url: 'https://classic.margonem.pl/img/barter-border.png',
		type: 'input',
	},
	{
		id: 'ornaments',
		name: 'Usuń ozdobniki okna gry',
		code: '.lt-hor, .lt-ver, .ld-hor, .ld-ver, .rt-hor, .rt-ver, .rd-hor, .rd-ver{display: none !important}',
		url: 'https://i.imgur.com/PCXtqMx.png',
		type: 'checkbox',
	},
	{
		id: 'hp-ornaments',
		name: 'Usuń ozdobniki HP',
		code: '#leorn1, #leorn2{display: none !important}',
		url: 'https://i.imgur.com/IrL3Aat.png',
		type: 'checkbox',
	},
];
export default data;
